# Child application for prometheus, within templates in apps folder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
        - $values/charts/prometheus/values.yaml
    - repoURL: 'https://git.example.com/org/value-files.git'
      targetRevision: dev
      ref: values  
  syncPolicy:
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference   
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default